packages:
  - packages/**
  - docs
  - e2e
  - i18n
  - server
  - plugins
  - web
  - .github
  - packages/*
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': false
  bcrypt: true
  better-sqlite3: true
  canvas: false
  core-js: false
  cpu-features: false
  es5-ext: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  ssh2: false
  utimes: false
  '@tailwindcss/oxide': true
  core-js-pure: false
  postman-code-generators: false
overrides:
  canvas: 3.2.3
  sharp: ^0.34.5
  brace-expansion: ^1.1.13
  dompurify: ^3.4.2
  follow-redirects: ^1.16.0
  ip-address: ^10.2.0
  lodash-es: ^4.18.1
  node-forge: ^1.4.0
  qs: ^6.14.2
  serialize-javascript: ^7.0.5
  socket.io-parser: ^4.2.6
  svgo: ^3.3.3
  tar: ^7.5.15
  '@sveltejs/kit>cookie': ^0.7.2
  bullmq>uuid: ^11.1.1
  mermaid>uuid: ^11.1.1
packageExtensions:
  nestjs-kysely:
    dependencies:
      tslib: '*'
  nestjs-otel:
    dependencies:
      tslib: '*'
  '@photo-sphere-viewer/equirectangular-video-adapter':
    dependencies:
      three: '*'
  '@photo-sphere-viewer/video-plugin':
    dependencies:
      three: '*'
  sharp:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  '@immich/ui':
    dependencies:
      tailwindcss: '>=4.1'
  tailwind-variants:
    dependencies:
      tailwindcss: '>=4.1'
  bcrypt:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  '@nestjs/swagger':
    peerDependencies:
      typescript: '*'
dedupePeerDependents: false
preferWorkspacePackages: true
injectWorkspacePackages: true
shamefullyHoist: false
verifyDepsBeforeRun: install
minimumReleaseAgeExclude:
  - '@immich/ui@0.83.0'
