-- NOTE: This file is auto generated by ./sql-generator

-- ActivityRepository.search
select
  "activity".*,
  to_json("user") as "user"
from
  "activity"
  inner join "user" as "user2" on "user2"."id" = "activity"."userId"
  and "user2"."deletedAt" is null
  inner join lateral (
    select
      "user2"."id",
      "user2"."name",
      "user2"."email",
      "user2"."avatarColor",
      "user2"."profileImagePath",
      "user2"."profileChangedAt"
    from
      (
        select
          1
      ) as "dummy"
  ) as "user" on true
  left join "asset" on "asset"."id" = "activity"."assetId"
where
  "activity"."albumId" = $1
  and "asset"."deletedAt" is null
  and not (
    exists (
      select
        1
      from
        asset_metadata
      where
        asset_metadata."assetId" = "asset"."id"
        and asset_metadata.key = $2
        and case
          when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
            )::boolean,
            false
          )
          else coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
            )::boolean,
            (
              asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
            )::boolean,
            false
          )
          or (
            coalesce(
              (
                asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
              )::boolean,
              false
            )
            and lower(
              coalesce(
                asset_metadata.value #>> '{description,result,safety,confidence}',
                ''
              )
            ) = 'high'
            and (
              exists (
                select
                  1
                from
                  jsonb_array_elements_text(
                    coalesce(
                      asset_metadata.value #> '{description,result,safety,indicators}',
                      '[]'::jsonb
                    )
                  ) as indicator (value)
                where
                  lower(
                    regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                  ) = any (
                    array[
                      $3,
                      $4,
                      $5,
                      $6,
                      $7,
                      $8,
                      $9,
                      $10,
                      $11,
                      $12,
                      $13,
                      $14,
                      $15,
                      $16,
                      $17
                    ]::text[]
                  )
              )
              or coalesce(
                asset_metadata.value #>> '{description,result,description}',
                ''
              ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
            )
          )
        end = true
    )
  )
order by
  "activity"."createdAt" asc

-- ActivityRepository.create
insert into
  "activity" ("albumId", "userId")
values
  ($1, $2)
returning
  *,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "activity"."userId"
      ) as obj
  ) as "user"

-- ActivityRepository.delete
delete from "activity"
where
  "id" = $1::uuid

-- ActivityRepository.getStatistics
select
  count(*) filter (
    where
      "activity"."isLiked" = $1
  ) as "comments",
  count(*) filter (
    where
      "activity"."isLiked" = $2
  ) as "likes"
from
  "activity"
  inner join "user" on "user"."id" = "activity"."userId"
  and "user"."deletedAt" is null
  left join "asset" on "asset"."id" = "activity"."assetId"
where
  "activity"."assetId" = $3
  and not (
    exists (
      select
        1
      from
        asset_metadata
      where
        asset_metadata."assetId" = "asset"."id"
        and asset_metadata.key = $4
        and case
          when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
            )::boolean,
            false
          )
          else coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
            )::boolean,
            (
              asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
            )::boolean,
            false
          )
          or (
            coalesce(
              (
                asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
              )::boolean,
              false
            )
            and lower(
              coalesce(
                asset_metadata.value #>> '{description,result,safety,confidence}',
                ''
              )
            ) = 'high'
            and (
              exists (
                select
                  1
                from
                  jsonb_array_elements_text(
                    coalesce(
                      asset_metadata.value #> '{description,result,safety,indicators}',
                      '[]'::jsonb
                    )
                  ) as indicator (value)
                where
                  lower(
                    regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                  ) = any (
                    array[
                      $5,
                      $6,
                      $7,
                      $8,
                      $9,
                      $10,
                      $11,
                      $12,
                      $13,
                      $14,
                      $15,
                      $16,
                      $17,
                      $18,
                      $19
                    ]::text[]
                  )
              )
              or coalesce(
                asset_metadata.value #>> '{description,result,description}',
                ''
              ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
            )
          )
        end = true
    )
  )
  and "activity"."albumId" = $20
  and (
    (
      "asset"."deletedAt" is null
      and "asset"."visibility" != 'locked'
    )
    or "asset"."id" is null
  )
