-- NOTE: This file is auto generated by ./sql-generator

-- BestPhotosRepository.getScore
select
  *
from
  "asset_best_photo_score"
where
  "assetId" = $1::uuid

-- BestPhotosRepository.upsertScore
insert into
  "asset_best_photo_score" (
    "assetId",
    "ownerId",
    "score",
    "aestheticScore",
    "technicalScore",
    "subjectScore",
    "diversityScore",
    "scoreVersion",
    "computedAt",
    "metadata",
    "bestFrameTimestampMs",
    "frameScore",
    "frameMetadata"
  )
values
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
  )
on conflict ("assetId") do update
set
  "ownerId" = "excluded"."ownerId",
  "score" = "excluded"."score",
  "aestheticScore" = "excluded"."aestheticScore",
  "technicalScore" = "excluded"."technicalScore",
  "subjectScore" = "excluded"."subjectScore",
  "diversityScore" = "excluded"."diversityScore",
  "scoreVersion" = "excluded"."scoreVersion",
  "computedAt" = "excluded"."computedAt",
  "metadata" = "excluded"."metadata",
  "bestFrameTimestampMs" = "excluded"."bestFrameTimestampMs",
  "frameScore" = "excluded"."frameScore",
  "frameMetadata" = "excluded"."frameMetadata",
  "updatedAt" = now()

-- BestPhotosRepository.getBestPhotos
select
  "asset".*,
  "asset_best_photo_score"."score" as "bestPhotoScore",
  "asset_best_photo_score"."aestheticScore" as "bestPhotoAestheticScore",
  "asset_best_photo_score"."technicalScore" as "bestPhotoTechnicalScore",
  "asset_best_photo_score"."subjectScore" as "bestPhotoSubjectScore",
  "asset_best_photo_score"."diversityScore" as "bestPhotoDiversityScore",
  "asset_best_photo_score"."scoreVersion" as "bestPhotoScoreVersion",
  "asset_best_photo_score"."computedAt" as "bestPhotoComputedAt",
  "asset_best_photo_score"."metadata" as "bestPhotoMetadata",
  "asset_best_photo_score"."bestFrameTimestampMs" as "bestPhotoBestFrameTimestampMs",
  "asset_best_photo_score"."frameScore" as "bestPhotoFrameScore",
  "asset_best_photo_score"."frameMetadata" as "bestPhotoFrameMetadata"
from
  "asset_best_photo_score"
  inner join "asset" on "asset"."id" = "asset_best_photo_score"."assetId"
where
  "asset_best_photo_score"."ownerId" = $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."deletedAt" is null
  and "asset"."status" = 'active'
  and "asset"."visibility" in ('timeline')
  and "asset"."type" = 'IMAGE'
  and "asset_best_photo_score"."score" >= $3
order by
  "asset_best_photo_score"."score" desc,
  "asset"."fileCreatedAt" desc
limit
  $4
offset
  $5

-- BestPhotosRepository.deleteForAssets
delete from "asset_best_photo_score"
where
  "assetId" = any ($1::uuid[])
