-- NOTE: This file is auto generated by ./sql-generator

-- MemoryRepository.statistics
select
  count(*) as "total"
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $1
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $2
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $3,
                            $4,
                            $5,
                            $6,
                            $7,
                            $8,
                            $9,
                            $10,
                            $11,
                            $12,
                            $13,
                            $14,
                            $15,
                            $16,
                            $17
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )

-- MemoryRepository.statistics (date filter)
select
  count(*) as "total"
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $1
  )
  and (
    "hideAt" is null
    or "hideAt" >= $2
  )
  and "deletedAt" is null
  and "ownerId" = $3
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $4
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $5,
                            $6,
                            $7,
                            $8,
                            $9,
                            $10,
                            $11,
                            $12,
                            $13,
                            $14,
                            $15,
                            $16,
                            $17,
                            $18,
                            $19
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )

-- MemoryRepository.search
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
          and not exists (
            select
              $17 as "one"
            from
              "asset_face"
              inner join "person" on "person"."id" = "asset_face"."personId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $18
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  "deletedAt" is null
  and "ownerId" = $19
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $20
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $21,
                            $22,
                            $23,
                            $24,
                            $25,
                            $26,
                            $27,
                            $28,
                            $29,
                            $30,
                            $31,
                            $32,
                            $33,
                            $34,
                            $35
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )
order by
  "memoryAt" desc

-- MemoryRepository.search (date filter)
select
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
          and not exists (
            select
              $17 as "one"
            from
              "asset_face"
              inner join "person" on "person"."id" = "asset_face"."personId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $18
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets",
  "memory".*
from
  "memory"
where
  (
    "showAt" is null
    or "showAt" <= $19
  )
  and (
    "hideAt" is null
    or "hideAt" >= $20
  )
  and "deletedAt" is null
  and "ownerId" = $21
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $22
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $23,
                            $24,
                            $25,
                            $26,
                            $27,
                            $28,
                            $29,
                            $30,
                            $31,
                            $32,
                            $33,
                            $34,
                            $35,
                            $36,
                            $37
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )
order by
  "memoryAt" desc

-- MemoryRepository.get
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $17
  and "deletedAt" is null
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $18
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $19,
                            $20,
                            $21,
                            $22,
                            $23,
                            $24,
                            $25,
                            $26,
                            $27,
                            $28,
                            $29,
                            $30,
                            $31,
                            $32,
                            $33
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )

-- MemoryRepository.update
update "memory"
set
  "ownerId" = $1,
  "isSaved" = $2
where
  "id" = $3
select
  "memory".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
        order by
          "asset"."fileCreatedAt" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "id" = $17
  and "deletedAt" is null
  and (
    not exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
      where
        "memory_asset"."memoriesId" = "memory"."id"
    )
    or exists (
      select
        "memory_asset"."memoriesId"
      from
        "memory_asset"
        inner join "asset" on "asset"."id" = "memory_asset"."assetId"
      where
        "memory_asset"."memoriesId" = "memory"."id"
        and "asset"."visibility" = 'timeline'
        and "asset"."deletedAt" is null
        and not (
          exists (
            select
              1
            from
              asset_metadata
            where
              asset_metadata."assetId" = "asset"."id"
              and asset_metadata.key = $18
              and case
                when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                  )::boolean,
                  false
                )
                else coalesce(
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                  )::boolean,
                  (
                    asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                  )::boolean,
                  false
                )
                or (
                  coalesce(
                    (
                      asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                    )::boolean,
                    false
                  )
                  and lower(
                    coalesce(
                      asset_metadata.value #>> '{description,result,safety,confidence}',
                      ''
                    )
                  ) = 'high'
                  and (
                    exists (
                      select
                        1
                      from
                        jsonb_array_elements_text(
                          coalesce(
                            asset_metadata.value #> '{description,result,safety,indicators}',
                            '[]'::jsonb
                          )
                        ) as indicator (value)
                      where
                        lower(
                          regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                        ) = any (
                          array[
                            $19,
                            $20,
                            $21,
                            $22,
                            $23,
                            $24,
                            $25,
                            $26,
                            $27,
                            $28,
                            $29,
                            $30,
                            $31,
                            $32,
                            $33
                          ]::text[]
                        )
                    )
                    or coalesce(
                      asset_metadata.value #>> '{description,result,description}',
                      ''
                    ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                  )
                )
              end = true
          )
        )
    )
  )

-- MemoryRepository.delete
delete from "memory"
where
  "id" = $1

-- MemoryRepository.getAssetIds
select
  "assetId"
from
  "memory_asset"
where
  "memoriesId" = $1
  and "assetId" in ($2)

-- MemoryRepository.addAssetIds
insert into
  "memory_asset" ("memoriesId", "assetId")
values
  ($1, $2)
