-- NOTE: This file is auto generated by ./sql-generator

-- StackRepository.search
select
  "stack".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*,
          to_json("exifInfo") as "exifInfo"
        from
          "asset"
          inner join lateral (
            select
              "asset_exif"."assetId",
              "asset_exif"."autoStackId",
              "asset_exif"."bitsPerSample",
              "asset_exif"."city",
              "asset_exif"."colorspace",
              "asset_exif"."country",
              "asset_exif"."dateTimeOriginal",
              "asset_exif"."description",
              "asset_exif"."exifImageHeight",
              "asset_exif"."exifImageWidth",
              "asset_exif"."exposureTime",
              "asset_exif"."fileSizeInByte",
              "asset_exif"."fNumber",
              "asset_exif"."focalLength",
              "asset_exif"."fps",
              "asset_exif"."iso",
              "asset_exif"."latitude",
              "asset_exif"."lensModel",
              "asset_exif"."livePhotoCID",
              "asset_exif"."longitude",
              "asset_exif"."make",
              "asset_exif"."model",
              "asset_exif"."modifyDate",
              "asset_exif"."orientation",
              "asset_exif"."profileDescription",
              "asset_exif"."projectionType",
              "asset_exif"."rating",
              "asset_exif"."state",
              "asset_exif"."tags",
              "asset_exif"."timeZone"
            from
              "asset_exif"
            where
              "asset_exif"."assetId" = "asset"."id"
          ) as "exifInfo" on true
        where
          "asset"."deletedAt" is null
          and "asset"."stackId" = "stack"."id"
          and "asset"."visibility" in ('archive', 'timeline')
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
      ) as agg
  ) as "assets"
from
  "stack"
  inner join "asset" as "primaryAsset" on "primaryAsset"."id" = "stack"."primaryAssetId"
where
  "stack"."ownerId" = $17
  and "primaryAsset"."deletedAt" is null
  and not (
    exists (
      select
        1
      from
        asset_metadata
      where
        asset_metadata."assetId" = "primaryAsset"."id"
        and asset_metadata.key = $18
        and case
          when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
            )::boolean,
            false
          )
          else coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
            )::boolean,
            (
              asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
            )::boolean,
            false
          )
          or (
            coalesce(
              (
                asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
              )::boolean,
              false
            )
            and lower(
              coalesce(
                asset_metadata.value #>> '{description,result,safety,confidence}',
                ''
              )
            ) = 'high'
            and (
              exists (
                select
                  1
                from
                  jsonb_array_elements_text(
                    coalesce(
                      asset_metadata.value #> '{description,result,safety,indicators}',
                      '[]'::jsonb
                    )
                  ) as indicator (value)
                where
                  lower(
                    regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                  ) = any (
                    array[
                      $19,
                      $20,
                      $21,
                      $22,
                      $23,
                      $24,
                      $25,
                      $26,
                      $27,
                      $28,
                      $29,
                      $30,
                      $31,
                      $32,
                      $33
                    ]::text[]
                  )
              )
              or coalesce(
                asset_metadata.value #>> '{description,result,description}',
                ''
              ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
            )
          )
        end = true
    )
  )

-- StackRepository.delete
delete from "stack"
where
  "id" = $1::uuid

-- StackRepository.getById
select
  *,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset".*,
          (
            select
              coalesce(json_agg(agg), '[]')
            from
              (
                select
                  "tag"."id",
                  "tag"."value",
                  "tag"."createdAt",
                  "tag"."updatedAt",
                  "tag"."color",
                  "tag"."parentId"
                from
                  "tag"
                  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
              ) as agg
          ) as "tags",
          to_json("exifInfo") as "exifInfo"
        from
          "asset"
          inner join lateral (
            select
              "asset_exif"."assetId",
              "asset_exif"."autoStackId",
              "asset_exif"."bitsPerSample",
              "asset_exif"."city",
              "asset_exif"."colorspace",
              "asset_exif"."country",
              "asset_exif"."dateTimeOriginal",
              "asset_exif"."description",
              "asset_exif"."exifImageHeight",
              "asset_exif"."exifImageWidth",
              "asset_exif"."exposureTime",
              "asset_exif"."fileSizeInByte",
              "asset_exif"."fNumber",
              "asset_exif"."focalLength",
              "asset_exif"."fps",
              "asset_exif"."iso",
              "asset_exif"."latitude",
              "asset_exif"."lensModel",
              "asset_exif"."livePhotoCID",
              "asset_exif"."longitude",
              "asset_exif"."make",
              "asset_exif"."model",
              "asset_exif"."modifyDate",
              "asset_exif"."orientation",
              "asset_exif"."profileDescription",
              "asset_exif"."projectionType",
              "asset_exif"."rating",
              "asset_exif"."state",
              "asset_exif"."tags",
              "asset_exif"."timeZone"
            from
              "asset_exif"
            where
              "asset_exif"."assetId" = "asset"."id"
          ) as "exifInfo" on true
        where
          "asset"."deletedAt" is null
          and "asset"."stackId" = "stack"."id"
          and "asset"."visibility" in ('archive', 'timeline')
          and not (
            exists (
              select
                1
              from
                asset_metadata
              where
                asset_metadata."assetId" = "asset"."id"
                and asset_metadata.key = $1
                and case
                  when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                    )::boolean,
                    false
                  )
                  else coalesce(
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                    )::boolean,
                    (
                      asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                    )::boolean,
                    false
                  )
                  or (
                    coalesce(
                      (
                        asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                      )::boolean,
                      false
                    )
                    and lower(
                      coalesce(
                        asset_metadata.value #>> '{description,result,safety,confidence}',
                        ''
                      )
                    ) = 'high'
                    and (
                      exists (
                        select
                          1
                        from
                          jsonb_array_elements_text(
                            coalesce(
                              asset_metadata.value #> '{description,result,safety,indicators}',
                              '[]'::jsonb
                            )
                          ) as indicator (value)
                        where
                          lower(
                            regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                          ) = any (
                            array[
                              $2,
                              $3,
                              $4,
                              $5,
                              $6,
                              $7,
                              $8,
                              $9,
                              $10,
                              $11,
                              $12,
                              $13,
                              $14,
                              $15,
                              $16
                            ]::text[]
                          )
                      )
                      or coalesce(
                        asset_metadata.value #>> '{description,result,description}',
                        ''
                      ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                    )
                  )
                end = true
            )
          )
      ) as agg
  ) as "assets"
from
  "stack"
  inner join "asset" as "primaryAsset" on "primaryAsset"."id" = "stack"."primaryAssetId"
where
  "id" = $17::uuid
  and "primaryAsset"."deletedAt" is null
  and not (
    exists (
      select
        1
      from
        asset_metadata
      where
        asset_metadata."assetId" = "primaryAsset"."id"
        and asset_metadata.key = $18
        and case
          when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
            )::boolean,
            false
          )
          else coalesce(
            (
              asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
            )::boolean,
            (
              asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
            )::boolean,
            false
          )
          or (
            coalesce(
              (
                asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
              )::boolean,
              false
            )
            and lower(
              coalesce(
                asset_metadata.value #>> '{description,result,safety,confidence}',
                ''
              )
            ) = 'high'
            and (
              exists (
                select
                  1
                from
                  jsonb_array_elements_text(
                    coalesce(
                      asset_metadata.value #> '{description,result,safety,indicators}',
                      '[]'::jsonb
                    )
                  ) as indicator (value)
                where
                  lower(
                    regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                  ) = any (
                    array[
                      $19,
                      $20,
                      $21,
                      $22,
                      $23,
                      $24,
                      $25,
                      $26,
                      $27,
                      $28,
                      $29,
                      $30,
                      $31,
                      $32,
                      $33
                    ]::text[]
                  )
              )
              or coalesce(
                asset_metadata.value #>> '{description,result,description}',
                ''
              ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
            )
          )
        end = true
    )
  )

-- StackRepository.getForAssetRemoval
select
  "stackId" as "id",
  "stack"."primaryAssetId"
from
  "asset"
  left join "stack" on "stack"."id" = "asset"."stackId"
where
  "asset"."id" = $1

-- StackRepository.merge
update "asset"
set
  "stackId" = $1
where
  "asset"."stackId" = $2
