-- NOTE: This file is auto generated by ./sql-generator

-- TagRepository.get
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "id" = $1

-- TagRepository.getByValue
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "userId" = $1
  and "value" = $2

-- TagRepository.upsertValue
begin
insert into
  "tag" ("userId", "value", "parentId")
values
  ($1, $2, $3)
on conflict ("userId", "value") do update
set
  "parentId" = $4
returning
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
rollback

-- TagRepository.getAll
select
  "tag"."id",
  "tag"."value",
  "tag"."createdAt",
  "tag"."updatedAt",
  "tag"."color",
  "tag"."parentId"
from
  "tag"
where
  "userId" = $1
  and (
    not exists (
      select
        1
      from
        tag_closure
        inner join tag_asset on tag_asset."tagId" = tag_closure.id_descendant
      where
        tag_closure.id_ancestor = "tag"."id"
    )
    or exists (
      select
        1
      from
        tag_closure
        inner join tag_asset on tag_asset."tagId" = tag_closure.id_descendant
      where
        tag_closure.id_ancestor = "tag"."id"
        and not exists (
          select
            1
          from
            asset as hidden_content_asset
          where
            hidden_content_asset.id = "tag_asset"."assetId"
            and (
              exists (
                select
                  1
                from
                  asset_metadata
                where
                  asset_metadata."assetId" = "hidden_content_asset"."id"
                  and asset_metadata.key = $2
                  and case
                    when asset_metadata.value #> '{nsfwDetection,review}' is not null then coalesce(
                      (
                        asset_metadata.value #>> '{nsfwDetection,review,isNsfw}'
                      )::boolean,
                      false
                    )
                    else coalesce(
                      (
                        asset_metadata.value #>> '{nsfwDetection,result,isNsfw}'
                      )::boolean,
                      (
                        asset_metadata.value #>> '{nsfwDetection,result,nsfw}'
                      )::boolean,
                      false
                    )
                    or (
                      coalesce(
                        (
                          asset_metadata.value #>> '{description,result,safety,is_nsfw_likely}'
                        )::boolean,
                        false
                      )
                      and lower(
                        coalesce(
                          asset_metadata.value #>> '{description,result,safety,confidence}',
                          ''
                        )
                      ) = 'high'
                      and (
                        exists (
                          select
                            1
                          from
                            jsonb_array_elements_text(
                              coalesce(
                                asset_metadata.value #> '{description,result,safety,indicators}',
                                '[]'::jsonb
                              )
                            ) as indicator (value)
                          where
                            lower(
                              regexp_replace(indicator.value, '[^a-z0-9_-]+', '-', 'g')
                            ) = any (
                              array[
                                $3,
                                $4,
                                $5,
                                $6,
                                $7,
                                $8,
                                $9,
                                $10,
                                $11,
                                $12,
                                $13,
                                $14,
                                $15,
                                $16,
                                $17
                              ]::text[]
                            )
                        )
                        or coalesce(
                          asset_metadata.value #>> '{description,result,description}',
                          ''
                        ) ~* '\m(naked|nude|nudity|genitals?|penis|vagina|buttocks?|sexual activity|sex toy|bondage|restrained|restraint)\M'
                      )
                    )
                  end = true
              )
            )
        )
    )
  )
order by
  "value"

-- TagRepository.create
insert into
  "tag" ("userId", "color", "value")
values
  ($1, $2, $3)
returning
  *

-- TagRepository.update
update "tag"
set
  "color" = $1
where
  "id" = $2
returning
  *

-- TagRepository.delete
delete from "tag"
where
  "id" = $1

-- TagRepository.addAssetIds
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)

-- TagRepository.removeAssetIds
delete from "tag_asset"
where
  "tagId" = $1
  and "assetId" in ($2)

-- TagRepository.upsertAssetIds
insert into
  "tag_asset" ("assetId", "tagIds")
values
  ($1, $2)
on conflict do nothing
returning
  *

-- TagRepository.replaceAssetTags
begin
delete from "tag_asset"
where
  "assetId" = $1
insert into
  "tag_asset" ("tagId", "assetId")
values
  ($1, $2)
on conflict do nothing
returning
  *
rollback
